-- Pantry App — Global Item Catalog Seed
-- Run this in the Supabase SQL Editor (New query → paste → Run)
-- ~500 common pantry items pre-loaded with category, unit, location, and emoji

insert into public.catalog (name, category, default_unit, default_location, emoji, tags) values

-- ── CANNED GOODS ──────────────────────────────────────────────────────────────
('Diced Tomatoes', 'Canned Goods', 'can', 'pantry', '🍅', ARRAY['pantry-staple']),
('Crushed Tomatoes', 'Canned Goods', 'can', 'pantry', '🍅', ARRAY['pantry-staple']),
('Tomato Paste', 'Canned Goods', 'can', 'pantry', '🍅', ARRAY['pantry-staple']),
('Tomato Sauce', 'Canned Goods', 'can', 'pantry', '🍅', ARRAY['pantry-staple']),
('Black Beans', 'Canned Goods', 'can', 'pantry', '🫘', ARRAY['protein', 'pantry-staple']),
('Kidney Beans', 'Canned Goods', 'can', 'pantry', '🫘', ARRAY['protein']),
('Pinto Beans', 'Canned Goods', 'can', 'pantry', '🫘', ARRAY['protein']),
('Chickpeas', 'Canned Goods', 'can', 'pantry', '🫘', ARRAY['protein']),
('Cannellini Beans', 'Canned Goods', 'can', 'pantry', '🫘', ARRAY['protein']),
('Refried Beans', 'Canned Goods', 'can', 'pantry', '🫘', ARRAY['protein']),
('Corn', 'Canned Goods', 'can', 'pantry', '🌽', ARRAY['vegetable']),
('Green Beans', 'Canned Goods', 'can', 'pantry', '🫘', ARRAY['vegetable']),
('Coconut Milk', 'Canned Goods', 'can', 'pantry', '🥥', ARRAY['cooking']),
('Coconut Cream', 'Canned Goods', 'can', 'pantry', '🥥', ARRAY['baking', 'cooking']),
('Chicken Broth', 'Canned Goods', 'carton', 'pantry', '🍲', ARRAY['cooking', 'pantry-staple']),
('Beef Broth', 'Canned Goods', 'carton', 'pantry', '🍲', ARRAY['cooking']),
('Vegetable Broth', 'Canned Goods', 'carton', 'pantry', '🍲', ARRAY['cooking']),
('Tuna', 'Canned Goods', 'can', 'pantry', '🐟', ARRAY['protein', 'pantry-staple']),
('Salmon', 'Canned Goods', 'can', 'pantry', '🐟', ARRAY['protein']),
('Sardines', 'Canned Goods', 'can', 'pantry', '🐟', ARRAY['protein']),
('Anchovies', 'Canned Goods', 'can', 'pantry', '🐟', ARRAY['cooking']),
('Canned Chicken', 'Canned Goods', 'can', 'pantry', '🍗', ARRAY['protein']),
('Pumpkin Puree', 'Canned Goods', 'can', 'pantry', '🎃', ARRAY['baking']),
('Artichoke Hearts', 'Canned Goods', 'can', 'pantry', '🌿', ARRAY['vegetable']),
('Olives', 'Canned Goods', 'jar', 'pantry', '🫒', ARRAY['snack']),
('Roasted Red Peppers', 'Canned Goods', 'jar', 'pantry', '🫑', ARRAY['cooking']),
('Sun-Dried Tomatoes', 'Canned Goods', 'jar', 'pantry', '🍅', ARRAY['cooking']),
('Jalapeños', 'Canned Goods', 'jar', 'pantry', '🌶️', ARRAY['spicy']),
('Chipotle Peppers in Adobo', 'Canned Goods', 'can', 'pantry', '🌶️', ARRAY['spicy', 'cooking']),
('Green Chiles', 'Canned Goods', 'can', 'pantry', '🌶️', ARRAY['cooking']),
('Cream of Mushroom Soup', 'Canned Goods', 'can', 'pantry', '🍄', ARRAY['cooking']),
('Tomato Soup', 'Canned Goods', 'can', 'pantry', '🍅', ARRAY['soup']),
('Chicken Noodle Soup', 'Canned Goods', 'can', 'pantry', '🍜', ARRAY['soup']),
('Evaporated Milk', 'Canned Goods', 'can', 'pantry', '🥛', ARRAY['baking']),
('Sweetened Condensed Milk', 'Canned Goods', 'can', 'pantry', '🥛', ARRAY['baking']),
('Applesauce', 'Canned Goods', 'jar', 'pantry', '🍎', ARRAY['snack']),
('Pineapple Chunks', 'Canned Goods', 'can', 'pantry', '🍍', ARRAY['fruit']),
('Mandarin Oranges', 'Canned Goods', 'can', 'pantry', '🍊', ARRAY['fruit']),
('Cranberry Sauce', 'Canned Goods', 'can', 'pantry', '🍒', ARRAY['holiday']),
('Water Chestnuts', 'Canned Goods', 'can', 'pantry', '🌿', ARRAY['asian-cooking']),
('Bamboo Shoots', 'Canned Goods', 'can', 'pantry', '🌿', ARRAY['asian-cooking']),
('Chili', 'Canned Goods', 'can', 'pantry', '🌶️', ARRAY['protein', 'quick-meal']),

-- ── DRY GOODS & GRAINS ────────────────────────────────────────────────────────
('White Rice', 'Dry Goods & Grains', 'lb', 'pantry', '🍚', ARRAY['pantry-staple', 'grain']),
('Brown Rice', 'Dry Goods & Grains', 'lb', 'pantry', '🍚', ARRAY['grain', 'whole-grain']),
('Jasmine Rice', 'Dry Goods & Grains', 'lb', 'pantry', '🍚', ARRAY['grain']),
('Basmati Rice', 'Dry Goods & Grains', 'lb', 'pantry', '🍚', ARRAY['grain']),
('Quinoa', 'Dry Goods & Grains', 'lb', 'pantry', '🌾', ARRAY['grain', 'protein', 'whole-grain']),
('Oats', 'Dry Goods & Grains', 'lb', 'pantry', '🌾', ARRAY['breakfast', 'pantry-staple']),
('Steel Cut Oats', 'Dry Goods & Grains', 'lb', 'pantry', '🌾', ARRAY['breakfast', 'whole-grain']),
('Cornmeal', 'Dry Goods & Grains', 'lb', 'pantry', '🌽', ARRAY['baking', 'grain']),
('Farro', 'Dry Goods & Grains', 'lb', 'pantry', '🌾', ARRAY['grain', 'whole-grain']),
('Barley', 'Dry Goods & Grains', 'lb', 'pantry', '🌾', ARRAY['grain', 'soup']),
('Spaghetti', 'Dry Goods & Grains', 'lb', 'pantry', '🍝', ARRAY['pasta', 'pantry-staple']),
('Penne', 'Dry Goods & Grains', 'lb', 'pantry', '🍝', ARRAY['pasta', 'pantry-staple']),
('Rigatoni', 'Dry Goods & Grains', 'lb', 'pantry', '🍝', ARRAY['pasta']),
('Linguine', 'Dry Goods & Grains', 'lb', 'pantry', '🍝', ARRAY['pasta']),
('Fettuccine', 'Dry Goods & Grains', 'lb', 'pantry', '🍝', ARRAY['pasta']),
('Farfalle', 'Dry Goods & Grains', 'lb', 'pantry', '🍝', ARRAY['pasta']),
('Rotini', 'Dry Goods & Grains', 'lb', 'pantry', '🍝', ARRAY['pasta']),
('Elbow Macaroni', 'Dry Goods & Grains', 'lb', 'pantry', '🍝', ARRAY['pasta', 'pantry-staple']),
('Orzo', 'Dry Goods & Grains', 'lb', 'pantry', '🍝', ARRAY['pasta']),
('Lasagna Noodles', 'Dry Goods & Grains', 'lb', 'pantry', '🍝', ARRAY['pasta']),
('Rice Noodles', 'Dry Goods & Grains', 'lb', 'pantry', '🍜', ARRAY['pasta', 'gluten-free']),
('Soba Noodles', 'Dry Goods & Grains', 'lb', 'pantry', '🍜', ARRAY['pasta', 'asian-cooking']),
('Ramen Noodles', 'Dry Goods & Grains', 'pack', 'pantry', '🍜', ARRAY['quick-meal']),
('Red Lentils', 'Dry Goods & Grains', 'lb', 'pantry', '🫘', ARRAY['protein', 'pantry-staple']),
('Green Lentils', 'Dry Goods & Grains', 'lb', 'pantry', '🫘', ARRAY['protein']),
('Split Peas', 'Dry Goods & Grains', 'lb', 'pantry', '🫛', ARRAY['protein', 'soup']),
('Dried Chickpeas', 'Dry Goods & Grains', 'lb', 'pantry', '🫘', ARRAY['protein']),
('Dried Black Beans', 'Dry Goods & Grains', 'lb', 'pantry', '🫘', ARRAY['protein']),
('Dried Pinto Beans', 'Dry Goods & Grains', 'lb', 'pantry', '🫘', ARRAY['protein']),
('Panko Breadcrumbs', 'Dry Goods & Grains', 'bag', 'pantry', '🍞', ARRAY['cooking']),
('Italian Breadcrumbs', 'Dry Goods & Grains', 'bag', 'pantry', '🍞', ARRAY['cooking']),
('Couscous', 'Dry Goods & Grains', 'lb', 'pantry', '🌾', ARRAY['grain', 'quick-meal']),
('Polenta', 'Dry Goods & Grains', 'lb', 'pantry', '🌽', ARRAY['grain']),
('Grits', 'Dry Goods & Grains', 'lb', 'pantry', '🌽', ARRAY['grain', 'breakfast']),

-- ── BAKING ────────────────────────────────────────────────────────────────────
('All-Purpose Flour', 'Baking', 'lb', 'pantry', '🌾', ARRAY['baking', 'pantry-staple']),
('Bread Flour', 'Baking', 'lb', 'pantry', '🌾', ARRAY['baking']),
('Whole Wheat Flour', 'Baking', 'lb', 'pantry', '🌾', ARRAY['baking', 'whole-grain']),
('Almond Flour', 'Baking', 'lb', 'pantry', '🌰', ARRAY['baking', 'gluten-free']),
('White Sugar', 'Baking', 'lb', 'pantry', '🍚', ARRAY['baking', 'pantry-staple']),
('Brown Sugar', 'Baking', 'lb', 'pantry', '🍯', ARRAY['baking', 'pantry-staple']),
('Powdered Sugar', 'Baking', 'lb', 'pantry', '🍚', ARRAY['baking']),
('Honey', 'Baking', 'jar', 'pantry', '🍯', ARRAY['sweetener', 'pantry-staple']),
('Maple Syrup', 'Baking', 'bottle', 'pantry', '🍁', ARRAY['sweetener', 'breakfast']),
('Baking Soda', 'Baking', 'each', 'pantry', '🫙', ARRAY['baking', 'pantry-staple']),
('Baking Powder', 'Baking', 'each', 'pantry', '🫙', ARRAY['baking', 'pantry-staple']),
('Active Dry Yeast', 'Baking', 'each', 'pantry', '🫙', ARRAY['baking', 'bread']),
('Cornstarch', 'Baking', 'each', 'pantry', '🌽', ARRAY['baking', 'thickener']),
('Cocoa Powder', 'Baking', 'lb', 'pantry', '🍫', ARRAY['baking']),
('Semi-Sweet Chocolate Chips', 'Baking', 'bag', 'pantry', '🍫', ARRAY['baking']),
('Dark Chocolate Chips', 'Baking', 'bag', 'pantry', '🍫', ARRAY['baking']),
('White Chocolate Chips', 'Baking', 'bag', 'pantry', '🍫', ARRAY['baking']),
('Vanilla Extract', 'Baking', 'bottle', 'pantry', '🫙', ARRAY['baking', 'pantry-staple']),
('Vegetable Oil', 'Baking', 'bottle', 'pantry', '🫙', ARRAY['baking', 'cooking', 'pantry-staple']),
('Canola Oil', 'Baking', 'bottle', 'pantry', '🫙', ARRAY['baking', 'cooking']),
('Coconut Oil', 'Baking', 'jar', 'pantry', '🥥', ARRAY['baking', 'cooking']),
('Cream of Tartar', 'Baking', 'each', 'pantry', '🫙', ARRAY['baking']),
('Agave Nectar', 'Baking', 'bottle', 'pantry', '🌵', ARRAY['sweetener']),
('Molasses', 'Baking', 'bottle', 'pantry', '🫙', ARRAY['baking', 'sweetener']),

-- ── CONDIMENTS & SAUCES ───────────────────────────────────────────────────────
('Ketchup', 'Condiments & Sauces', 'bottle', 'pantry', '🍅', ARRAY['condiment', 'pantry-staple']),
('Yellow Mustard', 'Condiments & Sauces', 'bottle', 'pantry', '🌭', ARRAY['condiment']),
('Dijon Mustard', 'Condiments & Sauces', 'bottle', 'pantry', '🌭', ARRAY['condiment']),
('Whole Grain Mustard', 'Condiments & Sauces', 'jar', 'pantry', '🌭', ARRAY['condiment']),
('Mayonnaise', 'Condiments & Sauces', 'jar', 'fridge', '🫙', ARRAY['condiment', 'pantry-staple']),
('Hot Sauce', 'Condiments & Sauces', 'bottle', 'pantry', '🌶️', ARRAY['condiment', 'spicy']),
('Sriracha', 'Condiments & Sauces', 'bottle', 'pantry', '🌶️', ARRAY['condiment', 'spicy']),
('Soy Sauce', 'Condiments & Sauces', 'bottle', 'pantry', '🫙', ARRAY['condiment', 'asian-cooking', 'pantry-staple']),
('Worcestershire Sauce', 'Condiments & Sauces', 'bottle', 'pantry', '🫙', ARRAY['condiment']),
('Fish Sauce', 'Condiments & Sauces', 'bottle', 'pantry', '🐟', ARRAY['asian-cooking']),
('Oyster Sauce', 'Condiments & Sauces', 'bottle', 'pantry', '🦪', ARRAY['asian-cooking']),
('Hoisin Sauce', 'Condiments & Sauces', 'bottle', 'pantry', '🫙', ARRAY['asian-cooking']),
('Teriyaki Sauce', 'Condiments & Sauces', 'bottle', 'pantry', '🫙', ARRAY['asian-cooking']),
('BBQ Sauce', 'Condiments & Sauces', 'bottle', 'pantry', '🍖', ARRAY['condiment']),
('Buffalo Sauce', 'Condiments & Sauces', 'bottle', 'pantry', '🌶️', ARRAY['condiment', 'spicy']),
('Pasta Sauce (Marinara)', 'Condiments & Sauces', 'jar', 'pantry', '🍝', ARRAY['pasta', 'pantry-staple']),
('Pasta Sauce (Arrabbiata)', 'Condiments & Sauces', 'jar', 'pantry', '🍝', ARRAY['pasta', 'spicy']),
('Pasta Sauce (Alfredo)', 'Condiments & Sauces', 'jar', 'pantry', '🍝', ARRAY['pasta']),
('Salsa', 'Condiments & Sauces', 'jar', 'pantry', '🍅', ARRAY['condiment', 'pantry-staple']),
('Tahini', 'Condiments & Sauces', 'jar', 'pantry', '🫙', ARRAY['condiment', 'middle-eastern']),
('Peanut Butter', 'Condiments & Sauces', 'jar', 'pantry', '🥜', ARRAY['pantry-staple', 'protein']),
('Almond Butter', 'Condiments & Sauces', 'jar', 'pantry', '🌰', ARRAY['protein']),
('Strawberry Jam', 'Condiments & Sauces', 'jar', 'pantry', '🍓', ARRAY['breakfast']),
('Raspberry Jam', 'Condiments & Sauces', 'jar', 'pantry', '🍓', ARRAY['breakfast']),
('Grape Jelly', 'Condiments & Sauces', 'jar', 'pantry', '🍇', ARRAY['breakfast']),
('Olive Oil', 'Condiments & Sauces', 'bottle', 'pantry', '🫒', ARRAY['cooking', 'pantry-staple']),
('Extra Virgin Olive Oil', 'Condiments & Sauces', 'bottle', 'pantry', '🫒', ARRAY['cooking', 'pantry-staple']),
('Sesame Oil', 'Condiments & Sauces', 'bottle', 'pantry', '🫙', ARRAY['asian-cooking']),
('Avocado Oil', 'Condiments & Sauces', 'bottle', 'pantry', '🥑', ARRAY['cooking']),
('Balsamic Vinegar', 'Condiments & Sauces', 'bottle', 'pantry', '🍶', ARRAY['cooking']),
('Red Wine Vinegar', 'Condiments & Sauces', 'bottle', 'pantry', '🍶', ARRAY['cooking']),
('Apple Cider Vinegar', 'Condiments & Sauces', 'bottle', 'pantry', '🍶', ARRAY['cooking']),
('Rice Vinegar', 'Condiments & Sauces', 'bottle', 'pantry', '🍶', ARRAY['asian-cooking']),
('Ranch Dressing', 'Condiments & Sauces', 'bottle', 'fridge', '🥗', ARRAY['condiment']),
('Caesar Dressing', 'Condiments & Sauces', 'bottle', 'fridge', '🥗', ARRAY['condiment']),
('Italian Dressing', 'Condiments & Sauces', 'bottle', 'fridge', '🥗', ARRAY['condiment']),
('Hummus', 'Condiments & Sauces', 'container', 'fridge', '🫘', ARRAY['snack', 'protein']),
('Coconut Aminos', 'Condiments & Sauces', 'bottle', 'pantry', '🫙', ARRAY['gluten-free']),
('Steak Sauce', 'Condiments & Sauces', 'bottle', 'pantry', '🥩', ARRAY['condiment']),

-- ── SNACKS ────────────────────────────────────────────────────────────────────
('Potato Chips', 'Snacks', 'bag', 'pantry', '🥔', ARRAY['snack']),
('Tortilla Chips', 'Snacks', 'bag', 'pantry', '🌽', ARRAY['snack', 'pantry-staple']),
('Pretzels', 'Snacks', 'bag', 'pantry', '🥨', ARRAY['snack']),
('Popcorn', 'Snacks', 'bag', 'pantry', '🍿', ARRAY['snack']),
('Microwave Popcorn', 'Snacks', 'pack', 'pantry', '🍿', ARRAY['snack', 'quick-meal']),
('Rice Cakes', 'Snacks', 'bag', 'pantry', '🍚', ARRAY['snack']),
('Granola Bars', 'Snacks', 'box', 'pantry', '🌾', ARRAY['snack', 'breakfast']),
('Protein Bars', 'Snacks', 'box', 'pantry', '💪', ARRAY['snack', 'protein']),
('Trail Mix', 'Snacks', 'bag', 'pantry', '🌰', ARRAY['snack']),
('Mixed Nuts', 'Snacks', 'can', 'pantry', '🌰', ARRAY['snack', 'protein']),
('Almonds', 'Snacks', 'bag', 'pantry', '🌰', ARRAY['snack', 'protein']),
('Cashews', 'Snacks', 'bag', 'pantry', '🌰', ARRAY['snack', 'protein']),
('Walnuts', 'Snacks', 'bag', 'pantry', '🌰', ARRAY['snack', 'protein']),
('Peanuts', 'Snacks', 'bag', 'pantry', '🥜', ARRAY['snack', 'protein']),
('Pistachios', 'Snacks', 'bag', 'pantry', '🌿', ARRAY['snack', 'protein']),
('Sunflower Seeds', 'Snacks', 'bag', 'pantry', '🌻', ARRAY['snack']),
('Pumpkin Seeds', 'Snacks', 'bag', 'pantry', '🎃', ARRAY['snack', 'protein']),
('Raisins', 'Snacks', 'bag', 'pantry', '🍇', ARRAY['snack', 'fruit']),
('Dried Cranberries', 'Snacks', 'bag', 'pantry', '🍒', ARRAY['snack', 'fruit']),
('Dried Mango', 'Snacks', 'bag', 'pantry', '🥭', ARRAY['snack', 'fruit']),
('Dates', 'Snacks', 'bag', 'pantry', '🌴', ARRAY['snack', 'fruit']),
('Dark Chocolate', 'Snacks', 'bar', 'pantry', '🍫', ARRAY['snack', 'treat']),
('Graham Crackers', 'Snacks', 'box', 'pantry', '🍪', ARRAY['snack', 'baking']),
('Crackers', 'Snacks', 'box', 'pantry', '🫙', ARRAY['snack', 'pantry-staple']),
('Beef Jerky', 'Snacks', 'bag', 'pantry', '🥩', ARRAY['snack', 'protein']),
('Seaweed Snacks', 'Snacks', 'pack', 'pantry', '🌊', ARRAY['snack']),
('Chia Seeds', 'Snacks', 'bag', 'pantry', '🌱', ARRAY['superfood', 'baking']),
('Flax Seeds', 'Snacks', 'bag', 'pantry', '🌱', ARRAY['superfood']),

-- ── BEVERAGES ─────────────────────────────────────────────────────────────────
('Coffee (Ground)', 'Beverages', 'lb', 'pantry', '☕', ARRAY['coffee', 'pantry-staple']),
('Coffee (Whole Bean)', 'Beverages', 'lb', 'pantry', '☕', ARRAY['coffee']),
('Instant Coffee', 'Beverages', 'each', 'pantry', '☕', ARRAY['coffee', 'quick-meal']),
('Black Tea', 'Beverages', 'box', 'pantry', '🍵', ARRAY['tea']),
('Green Tea', 'Beverages', 'box', 'pantry', '🍵', ARRAY['tea']),
('Herbal Tea', 'Beverages', 'box', 'pantry', '🍵', ARRAY['tea']),
('Chamomile Tea', 'Beverages', 'box', 'pantry', '🌼', ARRAY['tea']),
('Orange Juice', 'Beverages', 'carton', 'fridge', '🍊', ARRAY['breakfast', 'pantry-staple']),
('Apple Juice', 'Beverages', 'carton', 'pantry', '🍎', ARRAY['beverages']),
('Coconut Water', 'Beverages', 'carton', 'pantry', '🥥', ARRAY['hydration']),
('Sparkling Water', 'Beverages', 'pack', 'pantry', '💧', ARRAY['beverages']),
('Hot Chocolate Mix', 'Beverages', 'box', 'pantry', '☕', ARRAY['beverages', 'treat']),
('Protein Powder', 'Beverages', 'lb', 'pantry', '💪', ARRAY['protein', 'supplement']),
('Almond Milk', 'Beverages', 'carton', 'fridge', '🥛', ARRAY['dairy-free', 'pantry-staple']),
('Oat Milk', 'Beverages', 'carton', 'fridge', '🥛', ARRAY['dairy-free']),
('Soy Milk', 'Beverages', 'carton', 'fridge', '🥛', ARRAY['dairy-free', 'protein']),
('Kombucha', 'Beverages', 'bottle', 'fridge', '🫙', ARRAY['probiotic']),
('Electrolyte Packets', 'Beverages', 'box', 'pantry', '💧', ARRAY['hydration']),
('Lemonade Mix', 'Beverages', 'each', 'pantry', '🍋', ARRAY['beverages']),

-- ── FROZEN ────────────────────────────────────────────────────────────────────
('Chicken Breast', 'Frozen', 'lb', 'freezer', '🍗', ARRAY['protein', 'pantry-staple']),
('Chicken Thighs', 'Frozen', 'lb', 'freezer', '🍗', ARRAY['protein']),
('Chicken Tenders', 'Frozen', 'lb', 'freezer', '🍗', ARRAY['protein', 'quick-meal']),
('Chicken Wings', 'Frozen', 'lb', 'freezer', '🍗', ARRAY['protein']),
('Ground Beef', 'Frozen', 'lb', 'freezer', '🥩', ARRAY['protein', 'pantry-staple']),
('Ground Turkey', 'Frozen', 'lb', 'freezer', '🦃', ARRAY['protein']),
('Ground Pork', 'Frozen', 'lb', 'freezer', '🥩', ARRAY['protein']),
('Beef Steak', 'Frozen', 'lb', 'freezer', '🥩', ARRAY['protein']),
('Pork Chops', 'Frozen', 'lb', 'freezer', '🥩', ARRAY['protein']),
('Italian Sausage', 'Frozen', 'lb', 'freezer', '🌭', ARRAY['protein']),
('Breakfast Sausage', 'Frozen', 'lb', 'freezer', '🌭', ARRAY['protein', 'breakfast']),
('Bacon', 'Frozen', 'lb', 'freezer', '🥓', ARRAY['protein', 'breakfast']),
('Salmon Fillet', 'Frozen', 'lb', 'freezer', '🐟', ARRAY['protein', 'seafood']),
('Tilapia', 'Frozen', 'lb', 'freezer', '🐟', ARRAY['protein', 'seafood']),
('Cod', 'Frozen', 'lb', 'freezer', '🐟', ARRAY['protein', 'seafood']),
('Shrimp', 'Frozen', 'lb', 'freezer', '🍤', ARRAY['protein', 'seafood', 'pantry-staple']),
('Fish Sticks', 'Frozen', 'box', 'freezer', '🐟', ARRAY['quick-meal']),
('Frozen Pizza', 'Frozen', 'each', 'freezer', '🍕', ARRAY['quick-meal']),
('Frozen Waffles', 'Frozen', 'box', 'freezer', '🧇', ARRAY['breakfast', 'quick-meal']),
('Tater Tots', 'Frozen', 'bag', 'freezer', '🥔', ARRAY['side-dish', 'quick-meal']),
('French Fries', 'Frozen', 'bag', 'freezer', '🍟', ARRAY['side-dish', 'quick-meal']),
('Frozen Peas', 'Frozen', 'bag', 'freezer', '🫛', ARRAY['vegetable', 'pantry-staple']),
('Frozen Corn', 'Frozen', 'bag', 'freezer', '🌽', ARRAY['vegetable']),
('Frozen Broccoli', 'Frozen', 'bag', 'freezer', '🥦', ARRAY['vegetable', 'pantry-staple']),
('Frozen Spinach', 'Frozen', 'bag', 'freezer', '🥬', ARRAY['vegetable']),
('Frozen Mixed Vegetables', 'Frozen', 'bag', 'freezer', '🥦', ARRAY['vegetable', 'pantry-staple']),
('Frozen Edamame', 'Frozen', 'bag', 'freezer', '🫛', ARRAY['vegetable', 'protein']),
('Frozen Cauliflower', 'Frozen', 'bag', 'freezer', '🥦', ARRAY['vegetable']),
('Frozen Green Beans', 'Frozen', 'bag', 'freezer', '🫘', ARRAY['vegetable']),
('Frozen Strawberries', 'Frozen', 'bag', 'freezer', '🍓', ARRAY['fruit', 'smoothie']),
('Frozen Blueberries', 'Frozen', 'bag', 'freezer', '🫐', ARRAY['fruit', 'smoothie']),
('Frozen Mango', 'Frozen', 'bag', 'freezer', '🥭', ARRAY['fruit', 'smoothie']),
('Frozen Mixed Berries', 'Frozen', 'bag', 'freezer', '🍓', ARRAY['fruit', 'smoothie']),
('Frozen Peaches', 'Frozen', 'bag', 'freezer', '🍑', ARRAY['fruit']),
('Puff Pastry', 'Frozen', 'each', 'freezer', '🥐', ARRAY['baking']),
('Pie Crust', 'Frozen', 'each', 'freezer', '🥧', ARRAY['baking']),
('Ice Cream', 'Frozen', 'each', 'freezer', '🍦', ARRAY['treat', 'dessert']),
('Frozen Burritos', 'Frozen', 'each', 'freezer', '🌯', ARRAY['quick-meal']),
('Edamame in Shell', 'Frozen', 'bag', 'freezer', '🫛', ARRAY['snack', 'protein']),

-- ── DAIRY & REFRIGERATED ──────────────────────────────────────────────────────
('Milk (Whole)', 'Dairy & Refrigerated', 'gallon', 'fridge', '🥛', ARRAY['dairy', 'pantry-staple']),
('Milk (2%)', 'Dairy & Refrigerated', 'gallon', 'fridge', '🥛', ARRAY['dairy', 'pantry-staple']),
('Heavy Cream', 'Dairy & Refrigerated', 'carton', 'fridge', '🥛', ARRAY['dairy', 'cooking', 'baking']),
('Half and Half', 'Dairy & Refrigerated', 'carton', 'fridge', '🥛', ARRAY['dairy', 'coffee']),
('Sour Cream', 'Dairy & Refrigerated', 'each', 'fridge', '🫙', ARRAY['dairy', 'condiment']),
('Cream Cheese', 'Dairy & Refrigerated', 'each', 'fridge', '🧀', ARRAY['dairy', 'baking']),
('Greek Yogurt', 'Dairy & Refrigerated', 'each', 'fridge', '🥛', ARRAY['dairy', 'protein', 'breakfast']),
('Regular Yogurt', 'Dairy & Refrigerated', 'each', 'fridge', '🥛', ARRAY['dairy', 'breakfast']),
('Butter (Salted)', 'Dairy & Refrigerated', 'lb', 'fridge', '🧈', ARRAY['dairy', 'pantry-staple', 'baking']),
('Butter (Unsalted)', 'Dairy & Refrigerated', 'lb', 'fridge', '🧈', ARRAY['dairy', 'baking']),
('Cheddar Cheese', 'Dairy & Refrigerated', 'lb', 'fridge', '🧀', ARRAY['dairy', 'pantry-staple']),
('Mozzarella Cheese', 'Dairy & Refrigerated', 'lb', 'fridge', '🧀', ARRAY['dairy']),
('Parmesan Cheese', 'Dairy & Refrigerated', 'lb', 'fridge', '🧀', ARRAY['dairy', 'pasta']),
('Swiss Cheese', 'Dairy & Refrigerated', 'lb', 'fridge', '🧀', ARRAY['dairy']),
('Feta Cheese', 'Dairy & Refrigerated', 'lb', 'fridge', '🧀', ARRAY['dairy', 'salad']),
('Ricotta Cheese', 'Dairy & Refrigerated', 'each', 'fridge', '🧀', ARRAY['dairy', 'pasta', 'baking']),
('Cottage Cheese', 'Dairy & Refrigerated', 'each', 'fridge', '🧀', ARRAY['dairy', 'protein']),
('Goat Cheese', 'Dairy & Refrigerated', 'each', 'fridge', '🧀', ARRAY['dairy', 'salad']),
('String Cheese', 'Dairy & Refrigerated', 'each', 'fridge', '🧀', ARRAY['dairy', 'snack']),
('Sliced Deli Turkey', 'Dairy & Refrigerated', 'lb', 'fridge', '🦃', ARRAY['protein', 'lunch']),
('Sliced Deli Ham', 'Dairy & Refrigerated', 'lb', 'fridge', '🥩', ARRAY['protein', 'lunch']),
('Pepperoni', 'Dairy & Refrigerated', 'each', 'fridge', '🍕', ARRAY['protein']),
('Bacon', 'Dairy & Refrigerated', 'lb', 'fridge', '🥓', ARRAY['protein', 'breakfast', 'pantry-staple']),
('Eggs', 'Dairy & Refrigerated', 'each', 'fridge', '🥚', ARRAY['protein', 'pantry-staple', 'breakfast']),
('Egg Whites', 'Dairy & Refrigerated', 'carton', 'fridge', '🥚', ARRAY['protein']),
('Tofu', 'Dairy & Refrigerated', 'each', 'fridge', '🫙', ARRAY['protein', 'vegan']),
('Tempeh', 'Dairy & Refrigerated', 'each', 'fridge', '🫙', ARRAY['protein', 'vegan']),
('Fresh Pasta', 'Dairy & Refrigerated', 'each', 'fridge', '🍝', ARRAY['pasta', 'quick-meal']),
('Orange Juice (Fresh)', 'Dairy & Refrigerated', 'carton', 'fridge', '🍊', ARRAY['breakfast']),
('Prosciutto', 'Dairy & Refrigerated', 'each', 'fridge', '🥩', ARRAY['protein', 'charcuterie']),
('Salami', 'Dairy & Refrigerated', 'each', 'fridge', '🍕', ARRAY['protein', 'charcuterie']),

-- ── PRODUCE ───────────────────────────────────────────────────────────────────
('Bananas', 'Produce', 'bunch', 'pantry', '🍌', ARRAY['fruit', 'pantry-staple']),
('Apples', 'Produce', 'each', 'pantry', '🍎', ARRAY['fruit', 'pantry-staple']),
('Oranges', 'Produce', 'each', 'pantry', '🍊', ARRAY['fruit']),
('Lemons', 'Produce', 'each', 'pantry', '🍋', ARRAY['fruit', 'cooking', 'pantry-staple']),
('Limes', 'Produce', 'each', 'pantry', '🍋', ARRAY['fruit', 'cooking']),
('Avocado', 'Produce', 'each', 'pantry', '🥑', ARRAY['fruit', 'pantry-staple']),
('Tomatoes', 'Produce', 'lb', 'pantry', '🍅', ARRAY['vegetable', 'pantry-staple']),
('Cherry Tomatoes', 'Produce', 'each', 'fridge', '🍅', ARRAY['vegetable', 'salad']),
('Roma Tomatoes', 'Produce', 'lb', 'pantry', '🍅', ARRAY['vegetable', 'cooking']),
('Potatoes', 'Produce', 'lb', 'pantry', '🥔', ARRAY['vegetable', 'pantry-staple']),
('Sweet Potatoes', 'Produce', 'lb', 'pantry', '🍠', ARRAY['vegetable']),
('Yellow Onion', 'Produce', 'each', 'pantry', '🧅', ARRAY['vegetable', 'pantry-staple', 'cooking']),
('Red Onion', 'Produce', 'each', 'pantry', '🧅', ARRAY['vegetable', 'salad']),
('Green Onions', 'Produce', 'bunch', 'fridge', '🌿', ARRAY['vegetable', 'cooking']),
('Shallots', 'Produce', 'each', 'pantry', '🧅', ARRAY['vegetable', 'cooking']),
('Garlic', 'Produce', 'each', 'pantry', '🧄', ARRAY['vegetable', 'pantry-staple', 'cooking']),
('Ginger', 'Produce', 'each', 'fridge', '🫚', ARRAY['vegetable', 'cooking', 'asian-cooking']),
('Carrots', 'Produce', 'lb', 'fridge', '🥕', ARRAY['vegetable', 'pantry-staple']),
('Celery', 'Produce', 'bunch', 'fridge', '🌿', ARRAY['vegetable']),
('Broccoli', 'Produce', 'each', 'fridge', '🥦', ARRAY['vegetable', 'pantry-staple']),
('Cauliflower', 'Produce', 'each', 'fridge', '🥦', ARRAY['vegetable']),
('Brussels Sprouts', 'Produce', 'lb', 'fridge', '🥦', ARRAY['vegetable']),
('Spinach', 'Produce', 'bag', 'fridge', '🥬', ARRAY['vegetable', 'salad', 'pantry-staple']),
('Kale', 'Produce', 'bunch', 'fridge', '🥬', ARRAY['vegetable', 'salad']),
('Arugula', 'Produce', 'bag', 'fridge', '🥬', ARRAY['vegetable', 'salad']),
('Romaine Lettuce', 'Produce', 'each', 'fridge', '🥬', ARRAY['vegetable', 'salad']),
('Mixed Salad Greens', 'Produce', 'bag', 'fridge', '🥬', ARRAY['vegetable', 'salad', 'pantry-staple']),
('Cabbage', 'Produce', 'each', 'fridge', '🥬', ARRAY['vegetable', 'cooking']),
('Cucumber', 'Produce', 'each', 'fridge', '🥒', ARRAY['vegetable', 'salad']),
('Bell Pepper (Red)', 'Produce', 'each', 'fridge', '🫑', ARRAY['vegetable', 'cooking']),
('Bell Pepper (Green)', 'Produce', 'each', 'fridge', '🫑', ARRAY['vegetable', 'cooking']),
('Bell Pepper (Yellow)', 'Produce', 'each', 'fridge', '🫑', ARRAY['vegetable']),
('Jalapeño', 'Produce', 'each', 'fridge', '🌶️', ARRAY['vegetable', 'spicy']),
('Zucchini', 'Produce', 'each', 'fridge', '🥒', ARRAY['vegetable']),
('Yellow Squash', 'Produce', 'each', 'fridge', '🫛', ARRAY['vegetable']),
('Butternut Squash', 'Produce', 'each', 'pantry', '🎃', ARRAY['vegetable']),
('Eggplant', 'Produce', 'each', 'fridge', '🍆', ARRAY['vegetable']),
('Asparagus', 'Produce', 'bunch', 'fridge', '🥦', ARRAY['vegetable']),
('Mushrooms (White)', 'Produce', 'each', 'fridge', '🍄', ARRAY['vegetable', 'cooking']),
('Mushrooms (Cremini)', 'Produce', 'each', 'fridge', '🍄', ARRAY['vegetable', 'cooking']),
('Portobello Mushrooms', 'Produce', 'each', 'fridge', '🍄', ARRAY['vegetable']),
('Beets', 'Produce', 'bunch', 'fridge', '🟣', ARRAY['vegetable']),
('Corn (Fresh)', 'Produce', 'each', 'pantry', '🌽', ARRAY['vegetable']),
('Grapes', 'Produce', 'lb', 'fridge', '🍇', ARRAY['fruit', 'snack']),
('Strawberries', 'Produce', 'each', 'fridge', '🍓', ARRAY['fruit']),
('Blueberries', 'Produce', 'each', 'fridge', '🫐', ARRAY['fruit', 'breakfast']),
('Raspberries', 'Produce', 'each', 'fridge', '🍓', ARRAY['fruit']),
('Mango', 'Produce', 'each', 'pantry', '🥭', ARRAY['fruit', 'tropical']),
('Pineapple', 'Produce', 'each', 'pantry', '🍍', ARRAY['fruit', 'tropical']),
('Watermelon', 'Produce', 'each', 'pantry', '🍉', ARRAY['fruit']),
('Peaches', 'Produce', 'each', 'pantry', '🍑', ARRAY['fruit']),
('Pears', 'Produce', 'each', 'pantry', '🍐', ARRAY['fruit']),
('Kiwi', 'Produce', 'each', 'fridge', '🥝', ARRAY['fruit']),
('Fresh Basil', 'Produce', 'each', 'fridge', '🌿', ARRAY['herb', 'cooking']),
('Fresh Cilantro', 'Produce', 'bunch', 'fridge', '🌿', ARRAY['herb', 'cooking']),
('Fresh Parsley', 'Produce', 'bunch', 'fridge', '🌿', ARRAY['herb', 'cooking']),
('Fresh Rosemary', 'Produce', 'bunch', 'fridge', '🌿', ARRAY['herb', 'cooking']),
('Fresh Thyme', 'Produce', 'bunch', 'fridge', '🌿', ARRAY['herb', 'cooking']),
('Fresh Mint', 'Produce', 'bunch', 'fridge', '🌿', ARRAY['herb', 'beverages']),
('Fresh Dill', 'Produce', 'bunch', 'fridge', '🌿', ARRAY['herb', 'cooking']),
('Leeks', 'Produce', 'bunch', 'fridge', '🌿', ARRAY['vegetable', 'cooking']),
('Fennel', 'Produce', 'each', 'fridge', '🌿', ARRAY['vegetable']),
('Radishes', 'Produce', 'bunch', 'fridge', '🔴', ARRAY['vegetable', 'salad']),
('Green Beans (Fresh)', 'Produce', 'lb', 'fridge', '🫘', ARRAY['vegetable']),

-- ── MEAT & SEAFOOD ────────────────────────────────────────────────────────────
('Chicken Breast (Fresh)', 'Meat & Seafood', 'lb', 'fridge', '🍗', ARRAY['protein', 'pantry-staple']),
('Chicken Thighs (Fresh)', 'Meat & Seafood', 'lb', 'fridge', '🍗', ARRAY['protein']),
('Whole Chicken', 'Meat & Seafood', 'each', 'fridge', '🐔', ARRAY['protein']),
('Ground Beef (Fresh)', 'Meat & Seafood', 'lb', 'fridge', '🥩', ARRAY['protein', 'pantry-staple']),
('Ground Turkey (Fresh)', 'Meat & Seafood', 'lb', 'fridge', '🦃', ARRAY['protein']),
('Ribeye Steak', 'Meat & Seafood', 'lb', 'fridge', '🥩', ARRAY['protein']),
('Sirloin Steak', 'Meat & Seafood', 'lb', 'fridge', '🥩', ARRAY['protein']),
('Flank Steak', 'Meat & Seafood', 'lb', 'fridge', '🥩', ARRAY['protein']),
('Pork Tenderloin', 'Meat & Seafood', 'lb', 'fridge', '🥩', ARRAY['protein']),
('Pork Chops (Fresh)', 'Meat & Seafood', 'lb', 'fridge', '🥩', ARRAY['protein']),
('Italian Sausage (Fresh)', 'Meat & Seafood', 'lb', 'fridge', '🌭', ARRAY['protein']),
('Chorizo', 'Meat & Seafood', 'lb', 'fridge', '🌭', ARRAY['protein', 'spicy']),
('Salmon (Fresh)', 'Meat & Seafood', 'lb', 'fridge', '🐟', ARRAY['protein', 'seafood']),
('Shrimp (Fresh)', 'Meat & Seafood', 'lb', 'fridge', '🍤', ARRAY['protein', 'seafood']),
('Halibut', 'Meat & Seafood', 'lb', 'fridge', '🐟', ARRAY['protein', 'seafood']),
('Mahi-Mahi', 'Meat & Seafood', 'lb', 'fridge', '🐟', ARRAY['protein', 'seafood']),
('Cod', 'Meat & Seafood', 'lb', 'fridge', '🐟', ARRAY['protein', 'seafood']),
('Scallops', 'Meat & Seafood', 'lb', 'fridge', '🐚', ARRAY['protein', 'seafood']),
('Crab', 'Meat & Seafood', 'lb', 'fridge', '🦀', ARRAY['protein', 'seafood']),
('Lamb Chops', 'Meat & Seafood', 'lb', 'fridge', '🥩', ARRAY['protein']),
('Short Ribs', 'Meat & Seafood', 'lb', 'fridge', '🥩', ARRAY['protein']),
('Duck Breast', 'Meat & Seafood', 'lb', 'fridge', '🦆', ARRAY['protein']),
('Bratwurst', 'Meat & Seafood', 'lb', 'fridge', '🌭', ARRAY['protein']),

-- ── SPICES & SEASONINGS ───────────────────────────────────────────────────────
('Kosher Salt', 'Spices & Seasonings', 'each', 'spice_rack', '🧂', ARRAY['seasoning', 'pantry-staple']),
('Sea Salt', 'Spices & Seasonings', 'each', 'spice_rack', '🧂', ARRAY['seasoning']),
('Black Pepper', 'Spices & Seasonings', 'each', 'spice_rack', '🫙', ARRAY['seasoning', 'pantry-staple']),
('Red Pepper Flakes', 'Spices & Seasonings', 'each', 'spice_rack', '🌶️', ARRAY['seasoning', 'spicy']),
('Cayenne Pepper', 'Spices & Seasonings', 'each', 'spice_rack', '🌶️', ARRAY['seasoning', 'spicy']),
('Paprika', 'Spices & Seasonings', 'each', 'spice_rack', '🫙', ARRAY['seasoning', 'pantry-staple']),
('Smoked Paprika', 'Spices & Seasonings', 'each', 'spice_rack', '🫙', ARRAY['seasoning']),
('Garlic Powder', 'Spices & Seasonings', 'each', 'spice_rack', '🧄', ARRAY['seasoning', 'pantry-staple']),
('Onion Powder', 'Spices & Seasonings', 'each', 'spice_rack', '🧅', ARRAY['seasoning', 'pantry-staple']),
('Cumin', 'Spices & Seasonings', 'each', 'spice_rack', '🫙', ARRAY['seasoning', 'pantry-staple']),
('Coriander', 'Spices & Seasonings', 'each', 'spice_rack', '🌿', ARRAY['seasoning']),
('Turmeric', 'Spices & Seasonings', 'each', 'spice_rack', '🫙', ARRAY['seasoning', 'anti-inflammatory']),
('Curry Powder', 'Spices & Seasonings', 'each', 'spice_rack', '🫙', ARRAY['seasoning']),
('Garam Masala', 'Spices & Seasonings', 'each', 'spice_rack', '🫙', ARRAY['seasoning', 'indian-cooking']),
('Chili Powder', 'Spices & Seasonings', 'each', 'spice_rack', '🌶️', ARRAY['seasoning', 'pantry-staple']),
('Oregano', 'Spices & Seasonings', 'each', 'spice_rack', '🌿', ARRAY['seasoning', 'pantry-staple']),
('Basil (Dried)', 'Spices & Seasonings', 'each', 'spice_rack', '🌿', ARRAY['seasoning']),
('Thyme (Dried)', 'Spices & Seasonings', 'each', 'spice_rack', '🌿', ARRAY['seasoning']),
('Rosemary (Dried)', 'Spices & Seasonings', 'each', 'spice_rack', '🌿', ARRAY['seasoning']),
('Bay Leaves', 'Spices & Seasonings', 'each', 'spice_rack', '🍃', ARRAY['seasoning']),
('Parsley (Dried)', 'Spices & Seasonings', 'each', 'spice_rack', '🌿', ARRAY['seasoning']),
('Dill (Dried)', 'Spices & Seasonings', 'each', 'spice_rack', '🌿', ARRAY['seasoning']),
('Sage', 'Spices & Seasonings', 'each', 'spice_rack', '🌿', ARRAY['seasoning']),
('Italian Seasoning', 'Spices & Seasonings', 'each', 'spice_rack', '🌿', ARRAY['seasoning', 'pantry-staple']),
('Cinnamon (Ground)', 'Spices & Seasonings', 'each', 'spice_rack', '🫙', ARRAY['seasoning', 'baking', 'pantry-staple']),
('Nutmeg', 'Spices & Seasonings', 'each', 'spice_rack', '🫙', ARRAY['seasoning', 'baking']),
('Allspice', 'Spices & Seasonings', 'each', 'spice_rack', '🫙', ARRAY['seasoning', 'baking']),
('Cardamom', 'Spices & Seasonings', 'each', 'spice_rack', '🫙', ARRAY['seasoning', 'baking']),
('Ginger (Ground)', 'Spices & Seasonings', 'each', 'spice_rack', '🫚', ARRAY['seasoning', 'baking']),
('Cloves (Ground)', 'Spices & Seasonings', 'each', 'spice_rack', '🫙', ARRAY['seasoning', 'baking']),
('Fennel Seeds', 'Spices & Seasonings', 'each', 'spice_rack', '🌿', ARRAY['seasoning']),
('Mustard Seeds', 'Spices & Seasonings', 'each', 'spice_rack', '🌿', ARRAY['seasoning']),
('Sesame Seeds', 'Spices & Seasonings', 'each', 'spice_rack', '🌱', ARRAY['seasoning', 'asian-cooking']),
('Everything Bagel Seasoning', 'Spices & Seasonings', 'each', 'spice_rack', '🫙', ARRAY['seasoning']),
('Lemon Pepper', 'Spices & Seasonings', 'each', 'spice_rack', '🍋', ARRAY['seasoning']),
('Old Bay Seasoning', 'Spices & Seasonings', 'each', 'spice_rack', '🦀', ARRAY['seasoning', 'seafood']),
('Cajun Seasoning', 'Spices & Seasonings', 'each', 'spice_rack', '🌶️', ARRAY['seasoning', 'spicy']),
('Taco Seasoning', 'Spices & Seasonings', 'each', 'spice_rack', '🌮', ARRAY['seasoning']),
('Ranch Seasoning', 'Spices & Seasonings', 'each', 'spice_rack', '🫙', ARRAY['seasoning']),
('BBQ Seasoning', 'Spices & Seasonings', 'each', 'spice_rack', '🍖', ARRAY['seasoning']),
('Steak Seasoning', 'Spices & Seasonings', 'each', 'spice_rack', '🥩', ARRAY['seasoning']),
('Poultry Seasoning', 'Spices & Seasonings', 'each', 'spice_rack', '🍗', ARRAY['seasoning']),
('Pumpkin Pie Spice', 'Spices & Seasonings', 'each', 'spice_rack', '🎃', ARRAY['seasoning', 'baking']),
('Za''atar', 'Spices & Seasonings', 'each', 'spice_rack', '🌿', ARRAY['seasoning', 'middle-eastern']),
('Chinese Five Spice', 'Spices & Seasonings', 'each', 'spice_rack', '🫙', ARRAY['seasoning', 'asian-cooking']),
('White Pepper', 'Spices & Seasonings', 'each', 'spice_rack', '🫙', ARRAY['seasoning']),
('Nutritional Yeast', 'Spices & Seasonings', 'each', 'spice_rack', '🫙', ARRAY['vegan', 'umami']),
('Cinnamon Sticks', 'Spices & Seasonings', 'each', 'spice_rack', '🌿', ARRAY['seasoning', 'baking']),
('Poppy Seeds', 'Spices & Seasonings', 'each', 'spice_rack', '🌸', ARRAY['seasoning', 'baking']),
('Caraway Seeds', 'Spices & Seasonings', 'each', 'spice_rack', '🌿', ARRAY['seasoning']),
('Sumac', 'Spices & Seasonings', 'each', 'spice_rack', '🫙', ARRAY['seasoning', 'middle-eastern']),
('Star Anise', 'Spices & Seasonings', 'each', 'spice_rack', '⭐', ARRAY['seasoning', 'asian-cooking']),
('Saffron', 'Spices & Seasonings', 'each', 'spice_rack', '🌸', ARRAY['seasoning']),
('Celery Salt', 'Spices & Seasonings', 'each', 'spice_rack', '🧂', ARRAY['seasoning']),
('Smoked Salt', 'Spices & Seasonings', 'each', 'spice_rack', '🧂', ARRAY['seasoning']),
('Himalayan Pink Salt', 'Spices & Seasonings', 'each', 'spice_rack', '🩷', ARRAY['seasoning']),
('Herbes de Provence', 'Spices & Seasonings', 'each', 'spice_rack', '🌸', ARRAY['seasoning']),
('Fajita Seasoning', 'Spices & Seasonings', 'each', 'spice_rack', '🌮', ARRAY['seasoning']),
('Citric Acid', 'Spices & Seasonings', 'each', 'spice_rack', '🍋', ARRAY['baking', 'preservation']),

-- ── HOUSEHOLD & OTHER ─────────────────────────────────────────────────────────
('Paper Towels', 'Household & Other', 'roll', 'pantry', '🧻', ARRAY['household', 'pantry-staple']),
('Toilet Paper', 'Household & Other', 'roll', 'pantry', '🧻', ARRAY['household', 'pantry-staple']),
('Dish Soap', 'Household & Other', 'each', 'pantry', '🧴', ARRAY['household', 'pantry-staple']),
('Laundry Detergent', 'Household & Other', 'each', 'pantry', '🧺', ARRAY['household']),
('Fabric Softener', 'Household & Other', 'each', 'pantry', '🌸', ARRAY['household']),
('Dryer Sheets', 'Household & Other', 'box', 'pantry', '🌸', ARRAY['household']),
('Dishwasher Pods', 'Household & Other', 'each', 'pantry', '🫧', ARRAY['household', 'pantry-staple']),
('All-Purpose Cleaner', 'Household & Other', 'each', 'pantry', '🧴', ARRAY['household']),
('Bathroom Cleaner', 'Household & Other', 'each', 'pantry', '🧴', ARRAY['household']),
('Glass Cleaner', 'Household & Other', 'each', 'pantry', '🪟', ARRAY['household']),
('Disinfecting Wipes', 'Household & Other', 'each', 'pantry', '🧻', ARRAY['household']),
('Trash Bags', 'Household & Other', 'box', 'pantry', '🗑️', ARRAY['household', 'pantry-staple']),
('Gallon Zip Bags', 'Household & Other', 'box', 'pantry', '🫙', ARRAY['household']),
('Quart Zip Bags', 'Household & Other', 'box', 'pantry', '🫙', ARRAY['household']),
('Sandwich Bags', 'Household & Other', 'box', 'pantry', '🫙', ARRAY['household']),
('Plastic Wrap', 'Household & Other', 'each', 'pantry', '🫙', ARRAY['household']),
('Aluminum Foil', 'Household & Other', 'each', 'pantry', '🪩', ARRAY['household', 'pantry-staple']),
('Parchment Paper', 'Household & Other', 'each', 'pantry', '📄', ARRAY['household', 'baking']),
('Wax Paper', 'Household & Other', 'each', 'pantry', '📄', ARRAY['household', 'baking']),
('Paper Plates', 'Household & Other', 'pack', 'pantry', '🍽️', ARRAY['household']),
('Napkins', 'Household & Other', 'pack', 'pantry', '🧻', ARRAY['household']),
('Coffee Filters', 'Household & Other', 'box', 'pantry', '☕', ARRAY['household', 'coffee']),
('Hand Soap', 'Household & Other', 'each', 'pantry', '🧴', ARRAY['household', 'pantry-staple']),
('Ibuprofen', 'Household & Other', 'each', 'pantry', '💊', ARRAY['medicine']),
('Acetaminophen', 'Household & Other', 'each', 'pantry', '💊', ARRAY['medicine']),
('Antacids', 'Household & Other', 'each', 'pantry', '💊', ARRAY['medicine']),
('Multivitamins', 'Household & Other', 'each', 'pantry', '💊', ARRAY['supplement']),
('Vitamin D', 'Household & Other', 'each', 'pantry', '💊', ARRAY['supplement']),
('Fish Oil', 'Household & Other', 'each', 'pantry', '🐟', ARRAY['supplement']),
('Band-Aids', 'Household & Other', 'box', 'pantry', '🩹', ARRAY['medicine', 'first-aid']),
('Hydrogen Peroxide', 'Household & Other', 'each', 'pantry', '🫙', ARRAY['medicine', 'first-aid']),
('Rubbing Alcohol', 'Household & Other', 'each', 'pantry', '🫙', ARRAY['medicine', 'first-aid']),
('Allergy Medicine', 'Household & Other', 'each', 'pantry', '💊', ARRAY['medicine']),
('Bleach', 'Household & Other', 'each', 'pantry', '🧴', ARRAY['household']),
('Sponges', 'Household & Other', 'pack', 'pantry', '🧽', ARRAY['household']),
('Toothpaste', 'Household & Other', 'each', 'pantry', '🦷', ARRAY['household']),
('Shampoo', 'Household & Other', 'each', 'pantry', '🧴', ARRAY['household']),
('Conditioner', 'Household & Other', 'each', 'pantry', '🧴', ARRAY['household']),
('Body Wash', 'Household & Other', 'each', 'pantry', '🧴', ARRAY['household']),
('Deodorant', 'Household & Other', 'each', 'pantry', '🌸', ARRAY['household']),
('Probiotics', 'Household & Other', 'each', 'pantry', '🫙', ARRAY['supplement']);
